void draw_background(struct color layer[HEIGHT][WIDTH]);
void draw_cookieband(void);
void bake_cookie(struct color layer[HEIGHT][WIDTH]);
void bake_background_cookie(struct color layer[HEIGHT][WIDTH], int t);
void pour_milk(int t);
void draw_shine(int time,int wings);
void draw_glow_circle(void);
void draw_cursor(int x0, int y0);
void draw_pop_up(struct color layer[HEIGHT][WIDTH], int t);
void draw_pop_up_icon(struct color layer[HEIGHT][WIDTH], int x0, int y0);
